legales/urls.py
from django.contrib import admin
from django.urls import path

from .views import HomeView

urlpatterns = [
     path('', HomeView.as_view(), name='home'),
     path('admin/', admin.site.urls),
]

legales/models.py
from django import forms
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class ModifiedArrayField(ArrayField):
    def formfield(self, **kwargs):
        defaults = {
            "form_class": forms.MultipleChoiceField,
            "choices": self.base_field.choices,
            **kwargs
        }
        return super(ArrayField, self).formfield(**defaults)


class Company(models.Model):
    nombre = models.CharField(max_length=20)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class Jurisdiccion(models.Model):
    nombre = models.CharField(max_length=20)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class Abogado(models.Model):
    nombre = models.CharField(max_length=120)
    correo = models.CharField(max_length=120, blank=True, null=True)
    telefono1 = models.CharField(max_length=120, blank=True, null=True)
    telefono2 = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class BonoJus(models.Model):
    nombre = models.CharField(max_length=20)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class TipoProceso(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre

# class Oficio(models.Model):
#     nombre = models.CharField(max_length=20)
#     class Meta:
#         unique_together = [['nombre',]]
#     def __str__(self):
#         return str(self.id) + ' - ' + self.nombre


class EstadoProcesal(models.Model):
    nombre = models.CharField(max_length=40)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class ObservacionPMP(models.Model):
    nombre = models.CharField(max_length=80)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class EstadoNegociacion(models.Model):
    nombre = models.CharField(max_length=40)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class ObservacionPericia(models.Model):
    nombre = models.CharField(max_length=80)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class Causa(models.Model):
    LABEL_OFICIOS = (
        ("AFIP", "AFIP"),
        ("CENTRO MEDICO", "CENTRO MEDICO"),
        ("CORREO", "CORREO"),
        ("EMPLEADOR", "EMPLEADOR"),
        ("JUZGADO", "JUZGADO"),
        ("SRT", "SRT"),
        ("TRIBUNAL", "TRIBUNAL"),
    )
    fecha_derivacion = models.DateField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    asunto = models.IntegerField()
    caratula = models.CharField(max_length=280)
    expediente = models.CharField(max_length=40)
    jurisdiccion = models.ForeignKey(Jurisdiccion, on_delete=models.CASCADE)
    tribunal = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(1)])
    tipo_proceso = models.ForeignKey(TipoProceso, on_delete=models.CASCADE)
    fecha_inicio_demanda = models.DateField(null=True, blank=True)
    incapacidad_reclamada = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    lesiones_reclamada = models.CharField(max_length=380, blank=True, null=True)
    reclama_dano_sicologico = models.BooleanField(default=False, null=True)
    monto_demanda = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fecha_pmi = models.DateField(null=True, blank=True)
    porcentaje_srt = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    abogado = models.ForeignKey(Abogado, on_delete=models.CASCADE)
    bono_y_jus = models.ForeignKey(BonoJus, on_delete=models.CASCADE)
    monto_jus = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    monto_bono = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    detalle = models.CharField(max_length=280, blank=True, null=True)
    preexistencia = models.DecimalField(max_digits=14, decimal_places=2, default=0, null=True, blank=True)
    estado_procesal = models.ForeignKey(EstadoProcesal, models.SET_NULL, blank=True, null=True)
    negociable_pmo = models.BooleanField(default=False, null=True)
    negociable_pmp = models.BooleanField(default=False, null=True)
    observacion_pericia = models.CharField(max_length=120, blank=True, null=True)
    fecha_pedido_pmp = models.DateField(null=True, blank=True)
    fecha_asigno_pmp = models.DateField(null=True, blank=True)
    fecha_pmp = models.DateField(null=True, blank=True)
    porcentaje_pmp = models.DecimalField(max_digits=14, decimal_places=2, default=0, null=True, blank=True)
    monto_autorizado = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    estado_negociacion = models.ForeignKey(EstadoNegociacion, models.SET_NULL, blank=True, null=True)
    ofrecimiento = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    contra_oferta = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fecha_ultimo_ofrecimiento = models.DateField(null=True, blank=True)
    monto_acuerdo = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    fecha_presentacion_acuerdo = models.DateField(null=True, blank=True)
    hay_cbu = models.BooleanField(default=False, null=True)
    homologado = models.BooleanField(default=False, null=True)
    fecha_pedido_fondos = models.DateField(null=True, blank=True)
    fecha_venci_pago = models.DateField(null=True, blank=True)
    observacion = models.CharField(max_length=120, blank=True, null=True)
    ppmed = models.CharField(max_length=60, blank=True, null=True)
    ppsic = models.CharField(max_length=60, blank=True, null=True)
    pcont = models.CharField(max_length=60, blank=True, null=True)
    # oficios = models.ForeignKey(Oficio, models.SET_NULL, blank=True, null=True)
    oficios = ModifiedArrayField(
        models.CharField(
            choices=LABEL_OFICIOS,
            max_length=100,
            blank=True,
            null=True
        ),
        blank=True,
        null=True
    )
    confesional = models.BooleanField(default=False, null=True)
    testimonial = models.BooleanField(default=False, null=True)
    otras_pruebas = models.CharField(max_length=60, blank=True, null=True)
    sentencia = models.CharField(max_length=60, blank=True, null=True)
    pedido_fondos = models.CharField(max_length=60, blank=True, null=True)
    fecha_facturado = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = [['asunto',]]

    def __str__(self):
        return self.company.nombre + ' ' + str(self.asunto) + ' ' + self.caratula


class TipoVencimiento(models.Model):
    nombre = models.CharField(max_length=40)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class Vencimiento(models.Model):
    fecha = models.DateField()
    causa = models.ForeignKey(Causa, on_delete=models.CASCADE)
    tipoVencimiento = models.ForeignKey(TipoVencimiento,
                                        on_delete=models.CASCADE)

    class Meta:
        unique_together = [['fecha', 'causa', 'tipoVencimiento']]

    def __str__(self):
        return str(self.id)


class Excepcion(models.Model):
    nombre = models.CharField(max_length=120)

    class Meta:
        unique_together = [['nombre',]]

    def __str__(self):
        return str(self.id) + ' - ' + self.nombre


class ExcepcionCausa(models.Model):
    causa = models.ForeignKey(Causa, on_delete=models.CASCADE)
    excepcion = models.ForeignKey(Excepcion, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['causa', 'excepcion',]]

    def __str__(self):
        return str(self.id)

legales/views.py
from django import forms
from django.db.models import Q
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView
from dateutil.relativedelta import relativedelta
import datetime

from .models import Vencimiento, TipoVencimiento


class HomeFilterForm(forms.Form):
    fecInicio = forms.DateField(label='Fecha Inicio', required=True,
                                widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    fecFinal = forms.DateField(label='Fecha Final', required=True,
                               widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    tipoVenc = forms.ModelChoiceField(label='Tipo Vencimiento',
                                      queryset=TipoVencimiento.objects.all(),
                                      required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fecInicio'].initial = datetime.date.today() - relativedelta(days=1)
        self.fields['fecInicio'].widget.attrs['value'] = self.fields['fecInicio'].initial
        self.fields['fecFinal'].initial = datetime.date.today() + relativedelta(days=7)
        self.fields['fecFinal'].widget.attrs['value'] = self.fields['fecFinal'].initial


class HomeView(FormMixin, ListView):
    context_object_name = 'vencimiento_list'
    form_class = HomeFilterForm
    model = Vencimiento
    paginate_by = 50
    queryset = Vencimiento.objects.all()
    template_name = 'vencimientoList.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['form'] = HomeFilterForm(self.request.GET)
        return context

    def querysetWrap(self, prmFecInicio, prmFecFinal, prmTpVenc):
        # prepare filters to apply to queryset
        filters = {}
        if prmFecInicio:
            filters['fecha__gte'] = prmFecInicio
        else:
            filters['fecha__gte'] = datetime.date.today() - relativedelta(days=1)
        if prmFecFinal:
            filters['fecha__lte'] = prmFecFinal
        else:
            filters['fecha__lte'] = datetime.date.today() + relativedelta(days=7)
        if prmTpVenc:
            filters['tipoVencimiento'] = prmTpVenc

        if len(filters) == 0:
            # Genera una salida vacía, se debe seleccionar planta
            return Vencimiento.objects.filter(fecha__year=1900)

        return Vencimiento.objects.filter(Q(**filters)).order_by('fecha')
        # .order_by( '-activo__fecha_ingreso', 'activo__tipoActivo')

    def get_queryset(self):
        return self.querysetWrap(self.request.GET.get('fecInicio'),
                                 self.request.GET.get('fecFinal'),
                                 self.request.GET.get('tipoVenc'))

legales/templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.css"
      integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E="
      crossorigin="anonymous"
    />

    <title>{% block title %}B&A Consultores{% endblock %}</title>
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %}{% endblock %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"
      integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0/dist/chartjs-plugin-datalabels.min.js"
      integrity="sha256-3kSXcicezu2sKkkqQae/hgspQC+t6zkOA0rS7QtlSyE="
      crossorigin="anonymous"
    ></script>

    {% block script %} {% endblock %}
  </body>
</html>

legales/templates/causaList.html
{% extends 'base.html' %} {% block body %}

<div class="container">
  <div class="row">
    <div class="col text-center">
      <a href="/admin">Administración</a>
    </div>
  </div>
</div>

<div style="margin: 0 40px 0 40px">
  <div class="card card-block mt-3">
    <form action="" method="get" class="form-inline">
      {% csrf_token %} {% for field in form.visible_fields %}
      <div class="form-group m-4">{{ field.label_tag }}&nbsp;{{ field }}</div>
      {% endfor %}
      <hr class="separator" />
      <input type="submit" class="btn btn-primary btn-sm float-right" value="Filtrar" style="width: 100px" />
    </form>
  </div>

  {% include "paginacion.html" %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Compañía</th>
        <th scope="col">Asunto</th>
        <th scope="col">Carátula</th>
        <th scope="col" style="text-align: center">Fecha</th>
        <th scope="col">Tipo Estado</th>
      </tr>
    </thead>
    <tbody>
      {% for causa in causa_list %}
      <tr>
        <th scope="row">{{ page_obj.start_index | add:forloop.counter0 }}</th>
        <td>{{ causa.company }}</td>
        <td>{{ causa.asunto }}</td>
        <td>{{ causa.caratula }}</td>
        <td>{{ causa.fecha_derivacion|date:'d/m/Y' }}</td>
        <td>....</td>
        <!-- <td align="right">{{ activo.cantidad }}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "paginacion.html" %}
</div>

{% endblock %}

legales/templates/paginacion.html
<nav aria-label="Paginación" class="mt-4">
    {% if is_paginated %}
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% endif %}

            {% if page_obj.number|add:'-4' > 1 %}                
                <li class="page-item">
                    <a class="page-link" href="{{ request.get_full_path }}&page={{page_obj.number|add:'-5'}}">&hellip;</a>
                </li>
            {% endif %}            
            {% for i in paginator.page_range %}
                {% if i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                <li {% if page_obj.number == i %} class="page-item active" {% else %} class="page-item" {% endif %}>
                    <a class="page-link" href="{{ request.get_full_path }}&page={{i}}">{{ i }}</a>
                </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                <li class="page-item">
                    <a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.number|add:'5' }}">&hellip;</a>
                </li>
            {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

legales/templates/vencimientoList.html
{% extends 'base.html' %} {% block body %}
<div class="container">
  <div class="row">
    <div class="col text-center">
      <a href="/admin">Administración</a>
    </div>
  </div>
</div>

<div style="margin: 0 40px 0 40px">
  <div class="card card-block mt-3">
    <form action="" method="get" class="form-inline">
      {% csrf_token %} {% for field in form.visible_fields %}
      <div class="form-group m-4">{{ field.label_tag }}&nbsp;{{ field }}</div>
      {% endfor %}
      <hr class="separator" />
      <input type="submit" class="btn btn-primary btn-sm float-right" value="Filtrar" style="width: 100px" />
    </form>
  </div>

  {% include "paginacion.html" %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Compañía</th>
        <th scope="col">Asunto</th>
        <th scope="col">Carátula</th>
        <th scope="col" style="text-align: center">Fecha</th>
        <th scope="col">Tipo Estado</th>
      </tr>
    </thead>
    <tbody>
      {% for v in vencimiento_list %}
      <tr id="{% url 'admin:legales_causa_change' v.causa.id %}">
        <td scope="row">{{ page_obj.start_index | add:forloop.counter0 }}</td>
        <td>{{ v.causa.company.nombre }}</td>
        <td>{{ v.causa.asunto }}</td>
        <td>{{ v.causa.caratula }}</td>
        <td>{{ v.fecha|date:'d/m/Y' }}</td>
        <td>{{ v.tipoVencimiento.nombre }}</td>
        <!-- <td align="right">{{ activo.cantidad }}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "paginacion.html" %}
</div>

{% endblock %} {% block script %}
<script>
  $("tr").dblclick(function () {
    var url = $(this).attr("id") + "?_to_field=id&_popup=1";
    window.open(url, "popup_edit", "width=1200,height=900");
  });
</script>
{% endblock %}